// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRHB_1MfSebhGNRo5kDJKerfBIpgMw_qU',
    appId: '1:988459832439:web:392fbf07d0c0dc3dc72272',
    messagingSenderId: '988459832439',
    projectId: 'instagram-d2c10',
    authDomain: 'instagram-d2c10.firebaseapp.com',
    storageBucket: 'instagram-d2c10.firebasestorage.app',
    measurementId: 'G-Q0JPK8V2FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELho9ZHRieRCxox3LpKSBEctBHFtWEkE',
    appId: '1:988459832439:android:5feb5256ae8e4856c72272',
    messagingSenderId: '988459832439',
    projectId: 'instagram-d2c10',
    storageBucket: 'instagram-d2c10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKXGMZr_43qfr6pRt6NUP8r4oCn_FKWps',
    appId: '1:988459832439:ios:ad022b08baf14f8dc72272',
    messagingSenderId: '988459832439',
    projectId: 'instagram-d2c10',
    storageBucket: 'instagram-d2c10.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKXGMZr_43qfr6pRt6NUP8r4oCn_FKWps',
    appId: '1:988459832439:ios:ad022b08baf14f8dc72272',
    messagingSenderId: '988459832439',
    projectId: 'instagram-d2c10',
    storageBucket: 'instagram-d2c10.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRHB_1MfSebhGNRo5kDJKerfBIpgMw_qU',
    appId: '1:988459832439:web:cf634b2e9577b66bc72272',
    messagingSenderId: '988459832439',
    projectId: 'instagram-d2c10',
    authDomain: 'instagram-d2c10.firebaseapp.com',
    storageBucket: 'instagram-d2c10.firebasestorage.app',
    measurementId: 'G-PLJ72CV20P',
  );
}
